### ISSUE TITLE
No me linkea a las vistas con href <a>

### ISSUE THREAD

**Issue by pkecastillo** [pkecastillo/vinotecagarage#1]
En la vista: site_nav.php linea 24 de ejemplo genera el error:
```
Not Found
The requested URL /vinotecagarage/site/acercade was not found on this server.
```

```php
                <li class="active">
                    <a href="<?= base_url()?>">Inicio</a>
                </li>
                <li>
                    <a href="<?= site_url('site/acercade/');?>">Sobre Nosotros</a>
                </li>
```

Pero si funciona el base_url.

En el controlador está creada bien la funcion:

```php
    public function acercade()
    {
        $this->load->view("site_header");
        $this->load->view("site_nav");
        $this->load->view("site_acercade");
        $this->load->view("site_footer");
    }
```

**Comment by hkcoyant** [comment]
@pkecastillo en application/config/config.php realizar:

Linea 26:
$config['base_url'] = '';

Linea 38: 
$config['index_page'] = 'index.php';

**Comment by pkecastillo** [comment]
@hkcoyant hiciste las pruebas en tu maquina?.
Porque a mi no me está funcionando ni con lo que me recomendás.
Actualmente si pongo index.php me coloca en la URL index.php y no es lo que queria. Yo queria dejarla mas limpia a la URL.
Confirmame cualquier cosa. Abrazo

**Comment by pkecastillo** [comment]
@hkcoyant lo solucione colocando asi en config.php:
```php
$config['base_url'] = 'http://localhost:8088/vinotecagarage/';

$config['index_page'] = 'index.php';
```

Le puse el index como vos me dijiste. Ya me linkean bien los href con <?= base_url()?>

Gracias animal
